version: '2'
services:
  ping-server:
    build: .
    restart: always
    command: ./server/server
    ports:
      - "8080:8080"
    environment:
      PORT: 8080

# Update to user seperate client container      
      
#     volumes_from:
#       - client
# 
#   client:
#     build: client/
#     volumes:
#       - /src/dist
