version: '2'
services:
  ping-server:
    build: server/
    restart: always
    command: ./server/server
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    volumes:
      - client-dist:/go/client/dist:ro

  client:
    build: client/
    volumes:
      - client-dist:/src/dist

volumes:
  client-dist:
